---
- name: Create VM on Proxmox
  become: true
  become_user: root
  hosts: proxmox
  gather_facts: false

  vars:
    proxmox_api_user: "root"
    proxmox_api_password: "dcw9021#"
    proxmox_api_host: "192.168.0.145:8006"
    proxmox_api_realm: "pam"  # You can use other realms like pve or any other as per your Proxmox configuration

  tasks:
    - name: Create VM on Proxmox
      proxmox_kvm:
        node: "{{ proxmox_api_host }}"
        vmid: 1000  # Unique ID for the VM
        name: "testansible"
        ostemplate: "local:vztmpl/debian-12.0.0-amd64-netinst.iso"
        memory: 1024
        cores: 1
        net0: virtio,bridge=vmbr0
        onboot: yes
        state: present
        username: "{{ proxmox_api_user }}"
        password: "{{ proxmox_api_password }}"
        realm: "{{ proxmox_api_realm }}"
