- name: Proxmox stuff
  hosts: 192.168.0.145
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    
    - proxmox_kvm:
        api_user    : root@pam
        api_password: dcw9021#
        api_host    : 192.168.0.145
        clone       : ubuntu-cloud
        name        : 
        node        : pve1
        storage     : local-lvm
        format      : qcow2
        vmid        : 1000
        newid       : 

    - proxmox_kvm:
        api_user    : root@pam
        api_password: dcw9021#
        api_host    : 192.168.0.145
        name        : 
        node        : pve1
        state       : started
