- hosts: test
  become: true
  become_user: root
  tasks:
    - name: copy sudoers_david
      copy:
        src: files/sudoers_david
        dest: /etc/sudoers.d/david
        owner: root
        group: root
        mode: 0440
